### ISSUE TITLE
I regulary experience timeouts since few weeks

### ISSUE THREAD

**Issue by o-be-one** [fokkonaut/F-DDrace#22] opened 2020-09-30 18:51 UTC
Hello,

since few weeks it's impossible for me to stay online for more than 6h without time out.

On my side i've tried: 
- check internet stability: all good
- update graphic drivers: done
- update DDNet client: done
- change timeout codes: done

I haven't tried with another client yet, i may try it also.

Be aware that i often see few players going time out at the same time, sometime it includes me sometime not. Look like i'm not alone to feel like im got dropped from the server connections.

Thanks !

**Comment by ChillerDragon** [comment] 2020-09-30 22:31
Possibly unrelated to the modification and more an Issue on the hosting side. Or could you also reproduce this on unofficial F-DDrace servers?

**Comment by o-be-one** [comment] 2020-10-03 19:36
I've tried with my other computer at my gf's place, same issue with timeout :(.
Probably more related to hosting side yeah :/.

**Comment by ChillerDragon** [comment] 2020-11-18 09:15
I played like 3 days straight and did not notice anything. Since you did not provide any further testing with unofficial F-DDrace servers I am closing this now.

**Closed by ChillerDragon** 2020-11-18 09:15 UTC
